# syntax = docker/dockerfile:experimental
# Build Container
FROM golang:1.15.2 as builder

ENV GO111MODULE on
WORKDIR /go/src/bitbucket.org/latonaio

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o testclient ./test/testclient


# Runtime Container
FROM alpine:3.12

RUN apk add --no-cache libc6-compat

COPY --from=builder /go/src/bitbucket.org/latonaio/testclient .

CMD ["./testclient"]
